### ISSUE TITLE
Existing connection error

### ISSUE THREAD

**Issue by CountParadox** [aerouk/imageserve#5]
Hi all, I just did a fresh install of the latest revision, and im getting this error

Message:
Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   at UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method)

does this imply that my previous attempt to install still has the connection open?  o.o

**Comment by aerouk** [comment]
It's been a year so I guess this is a non-issue now
