### ISSUE TITLE
Error uploading to nginx? 

### ISSUE THREAD

**Issue by SlimShadyIAm** [aerouk/imageserve#54]
Hi there. I followed the video tutorial but I get the following error:
```
Error: Message:
The remote server returned an error: (405) Method Not Allowed.

Request URL:
https://memes.slimshadyime.me/imageserve/upload.php

Response:
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

**Comment by SlimShadyIAm** [comment]
Solved this by using this config: https://github.com/aerouk/imageserve/issues/49 as well as enabling PHP
